import { TData } from "./Data";

export const dataPoker: TData = [
    {
        id: 1,
        question: 'Do you want to make extra money playing poker?',
        answers: [
            {
                answer: 'yes',
                img: '',
                emoji: '🤑',
                to: '/2',
                ym: 'extraMoneyWithPoker/yes',
                exit: '',
            },
            {
                answer: 'no',
                img: '',
                emoji: '😕',
                to: '/2',
                ym: 'extraMoneyWithPoker/no',
                exit: 'other',
            },
        ],
    },
    {
        id: 2,
        question: 'What is your experience?',
        answers: [
            {
                answer: 'I rarely play',
                img: '',
                emoji: '😬',
                to: '/3',
                ym: 'experience/rarely',
                exit: '',
            },
            {
                answer: 'Im decent',
                img: '',
                emoji: '🤔',
                to: '/3',
                ym: 'experience/sometimes',
                exit: '',
            },
            {
                answer: 'Im good',
                img: '',
                emoji: '😏',
                to: '/3',
                ym: 'experience/occasionally',
                exit: '',
            },
            {
                answer: 'Im pro',
                img: '',
                emoji: '😎',
                to: '/3',
                ym: 'experience/professional',
                exit: '',
            }
        ],
    },
    {
        id: 3,
        question: 'Which card is the highest?',
        answers: [
            {
                answer: 'Queen',
                img: '/queen.svg',
                emoji: '',
                to: '/4',
                ym: 'highest/queen',
                exit: '',
            },
            {
                answer: 'Jack',
                img: '/jack.svg',
                emoji: '',  
                to: '/4',
                ym: 'highest/jack',
                exit: '',
            },
            {
                answer: 'King',
                img: '/king.svg',
                emoji: '',
                to: '/4',
                ym: 'highest/king',
                exit: '',
            },
            {
                answer: 'Ace',
                img: '/ace.svg',
                emoji: '',
                to: '/4',
                ym: 'highest/ace',
                exit: '',
            },
        ],
    },
    {
        id: 4,
        question: 'Which hand is better?',
        answers: [
            {
                answer: 'Flush',
                img: '/flush.svg',
                emoji: '',
                to: '/5',
                ym: 'hand/flush',
                exit: '',
            },
            {
                answer: 'Full House',
                img: '/fullHouse.svg',
                emoji: '',  
                to: '/5',
                ym: 'hand/house',
                exit: '',
            },
            {
                answer: 'Straight',
                img: '/straight.svg',
                emoji: '',
                to: '/5',
                ym: 'hand/straight',
                exit: '',
            },
            {
                answer: 'Four of a Kind',
                img: '/4ofKind.svg',
                emoji: '',
                to: '/5',
                ym: 'hand/kare',
                exit: '',
            },
        ],
    },
    {
        id: 5,
        question: 'Do you know how to bluff?',
        answers: [
            {
                answer: 'yes',
                img: '',
                emoji: '😏',
                to: '/age',
                ym: 'bluff/yes',
                exit: '',
            },
            {
                answer: 'no',
                img: '',
                emoji: '😕',
                to: '/age',
                ym: 'bluff/no',
                exit: '',
            },
        ],
    },
]